export const listForCategory = [
    {
        id: 1,
        genre: 'Action',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/action/1max.png',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/action/1max.png',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/action/2max.png',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/action/2max.png',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/action/3max.png',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/action/3max.png',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/action/4max.png',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/action/4max.png',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ],
    },
    {
        id: 2,
        genre: 'Adventure',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/adventure/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/adventure/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/adventure/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/adventure/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/adventure/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/adventure/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/adventure/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/adventure/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 3,
        genre: 'Animation',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/animation/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/animation/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/animation/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/animation/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/animation/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/animation/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/animation/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/animation/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 4,
        genre: 'Comedy',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/comedy/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/comedy/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/comedy/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/comedy/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/comedy/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/comedy/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/comedy/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/comedy/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 5,
        genre: 'Crime',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/crime/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/crime/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/crime/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/crime/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/crime/3min.png',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/crime/3min.png',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/crime/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/crime/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 6,
        genre: 'Documentary',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/documentary/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/documentary/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/documentary/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/documentary/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/documentary/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/documentary/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/documentary/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/documentary/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 7,
        genre: 'Drama',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/drama/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/drama/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/drama/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/drama/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/drama/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/drama/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/drama/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/drama/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 8,
        genre: 'Family',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/family/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/family/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/family/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/family/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/family/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/family/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/family/4min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/family/4min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 9,
        genre: 'Fantasy',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/fantasy/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/fantasy/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/fantasy/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/fantasy/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/fantasy/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/fantasy/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/fantasy/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/fantasy/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 10,
        genre: 'History',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/history/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/history/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/history/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/history/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/history/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/history/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/history/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/history/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 11,
        genre: 'Horror',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/horror/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/horror/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/horror/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/horror/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/horror/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/horror/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/horror/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/horror/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 12,
        genre: 'Music',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/music/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/music/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/music/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/music/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/music/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/music/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/music/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/music/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 13,
        genre: 'Mystery',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/mystery/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/mystery/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/mystery/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/mystery/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/mystery/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/mystery/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/mystery/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/mystery/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 14,
        genre: 'Romance',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/romance/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/romance/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/romance/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/romance/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/romance/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/romance/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/romance/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/romance/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 15,
        genre: 'Science Fiction',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/scienceFiction/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/scienceFiction/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/scienceFiction/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/scienceFiction/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/scienceFiction/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/scienceFiction/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/scienceFiction/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/scienceFiction/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 16,
        genre: 'TV Movie',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/TVMovie/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/TVMovie/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/TVMovie/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/TVMovie/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/TVMovie/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/TVMovie/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/TVMovie/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/TVMovie/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 17,
        genre: 'Thriller',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/thriller/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/thriller/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/thriller/2min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/thriller/2min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/thriller/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/thriller/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/thriller/4min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/thriller/4min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 18,
        genre: 'War',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/war/1min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/war/1min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/war/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/war/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/war/3min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/war/3min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/war/4min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/war/4min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
    {
        id: 19,
        genre: 'Western',
        arr: [
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/western/1min.jpg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/western/1min.jpg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/western/2min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/western/2min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/western/3min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/western/3min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            },
            {
                adult: false,
                backdrop_path: '/images/homePage/imageForCategory/western/4min.jpeg',
                genre_ids: [28, 12, 18],
                id: 558449,
                original_language: "en",
                original_title: "Gladiator II",
                overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
                popularity: 5216.455,
                poster_path: '/images/homePage/imageForCategory/western/4min.jpeg',
                release_date: "2024-11-05",
                title: "Gladiator II",
                video: false,
                vote_average: 6.761,
                vote_count: 2024
            }
        ]
    },
];